pdf:
	xelatex -halt-on-error -output-directory output erl_elx_rubizza_hangout.tex

clean:
	cd output; rm *.aux *.log *.nav *.out *.snm *.toc *.vrb

show:
	evince output/erl_elx_rubizza_hangout.pdf


# LaTex:
# apt-get install texlive-full
# Ставит 5Гб чего-то там. Может стоит не full, а как-то более избирательно :)
#
# Beamer:
# apt-get install info-beamer
